log_dir: ${oc.env:ROOT,.}/logs

training:
  max_round: 2
  max_stage: 1
  num_generations: 3
  num_transplant_trees: 2
  seed: 561

game_manager:
  _target_: genrl.examples.code_generation.solver_manager.CodeGenerationGameManager
  max_stage: ${training.max_stage}
  max_round: ${training.max_round}
  game_state: 
    _target_: genrl.state.GameState
    round: 0
    stage: 0
  reward_manager:
    _target_: genrl.rewards.DefaultRewardManager
    reward_fn_store:
      _target_: genrl.rewards.reward_store.RewardFnStore
      max_rounds: ${training.max_round}
      reward_fn_stores:
        - _target_: genrl.rewards.reward_store.RoundRewardFnStore
          num_stages: ${training.max_stage}
          reward_fns:
            - _target_: genrl.examples.code_generation.solver_rewards.CodeGenerationRewards
  trainer:
    _target_: genrl.trainer.grpo_trainer.GRPOLanguageTrainerModule
    models:
      - _target_: transformers.AutoModelForCausalLM.from_pretrained
        pretrained_model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
    config:
      _target_: genrl.trainer.grpo_trainer.GRPOTrainerConfig
      epsilon: 0.2
      epsilon_high: 0.28
      beta: 0.0
      num_generations: ${training.num_generations}
      dtype: bfloat16
    log_with: tensorboard
    log_dir: ${log_dir}
  data_manager:
    _target_: genrl.examples.code_generation.solver_data.CodeGenerationDataManager
    system_prompt: 'solver'
    batch_size: 2
    local_batch_size: 1
    proposer_batch_size: 1
    num_generations: ${training.num_generations}
    num_transplant_trees: ${training.num_transplant_trees}
  communication:
    _target_: genrl.communication.hivemind.hivemind_backend.HivemindBackend
    get_retries: 1
  run_mode: "train"


proposer:
  _target_: genrl.examples.code_generation.proposer_service.ProposerService
  service_config:
    _target_: genrl.examples.code_generation.proposer_service.ProposerServiceConfig
    model: Qwen/Qwen3-4B-Instruct-2507
    num_proposals: 3
    train_batch_size: 3   
    identity_path: null
    startup_timeout: 120
    beam_size: 10
    get_retries: 0
    do_training: true
  ppo_config:
    _target_: genrl.examples.code_generation.proposer.PPOConfig
  vllm_config:
    _target_: genrl.examples.code_generation.proposer.VllmConfig
